[tool.poetry]
name = "repl_python3_Vynx-Staff-Apps"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^1.7.3"
Flask = "^2.0.2"
typing-extensions = "^4.0.1"
python-dotenv = "^0.19.2"
dta = "^1.3.1"
aiofiles = "^0.8.0"
"discord.py" = {git = "https://github.com/Rapptz/discord.py"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
